Create dist folder when testing if it doesn't already exist
Fixes:
error: proc macro panicked
  --> src/main.rs:86:14
   |
86 |         .run(tauri::generate_context!())
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: The `distDir` configuration is set to `"../dist"` but this path doesn't exist